---

- name: "Copy zipped artifact"
  template:
    src: ./artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: "Extract artifact"
  shell: tar -zxf artifact.tar.gz

- name: "Run npm install"
  shell: npm install

- name: "Stop application"
  shell: pm2 stop default

- name: "Start application"
  shell: pm2 start npm -- start
